export const gameTypes = {
  FETCH_NEWEST_GAMES: 'FETCH_NEWEST_GAMES',
  FETCH_POPULAR_GAMES: 'FETCH_POPULAR_GAMES',
  FETCH_UPCOMING_GAMES: 'FETCH_UPCOMING_GAMES',
  CACHE_GAME_DATA: 'CACHE_GAME_DATA',
};
